<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="1" ignored="3" total="5" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="46547" started-at="2018-04-21T15:06:49Z" finished-at="2018-04-21T15:07:36Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="46547" started-at="2018-04-21T15:06:49Z" finished-at="2018-04-21T15:07:36Z">
      <class name="testcases.CreateAccountPOM">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testcases.CreateAccountPOM@1846619]" name="beforeSuite" is-config="true" duration-ms="138" started-at="2018-04-21T20:36:49Z" finished-at="2018-04-21T20:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testcases.MergeAccountPOM@1ec1f0c]" name="setData" is-config="true" duration-ms="0" started-at="2018-04-21T20:36:49Z" finished-at="2018-04-21T20:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="setData()[pri:0, instance:testcases.CreateAccountPOM@1846619]" name="setData" is-config="true" duration-ms="0" started-at="2018-04-21T20:36:49Z" finished-at="2018-04-21T20:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.CreateAccountPOM@1846619]" name="beforeClass" is-config="true" duration-ms="2" started-at="2018-04-21T20:36:49Z" finished-at="2018-04-21T20:36:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testcases.CreateAccountPOM@1846619]" name="beforeMethod" is-config="true" duration-ms="9380" started-at="2018-04-21T20:36:49Z" finished-at="2018-04-21T20:36:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="createAccount()[pri:0, instance:testcases.CreateAccountPOM@1846619]" name="createAccount" duration-ms="20273" started-at="2018-04-21T20:36:58Z" finished-at="2018-04-21T20:37:19Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Unexpected result for screenshot command: null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Unexpected result for screenshot command: null
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:300)
	at wdMethods.SeMethods.takeSnap(SeMethods.java:362)
	at utils.Reporter.reportStep(Reporter.java:49)
	at utils.Reporter.reportStep(Reporter.java:70)
	at wdMethods.SeMethods.selectDropDownUsingText(SeMethods.java:187)
	at pages.AccountsPage.selectIndustry(AccountsPage.java:46)
	at testcases.CreateAccountPOM.createAccount(CreateAccountPOM.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccount -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:testcases.CreateAccountPOM@1846619]" name="afterMethod" is-config="true" duration-ms="714" started-at="2018-04-21T20:37:19Z" finished-at="2018-04-21T20:37:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:testcases.CreateAccountPOM@1846619]" name="afterTest" is-config="true" duration-ms="0" started-at="2018-04-21T20:37:36Z" finished-at="2018-04-21T20:37:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="SKIP" signature="afterSuite()[pri:0, instance:testcases.CreateAccountPOM@1846619]" name="afterSuite" is-config="true" duration-ms="0" started-at="2018-04-21T20:37:36Z" finished-at="2018-04-21T20:37:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- testcases.CreateAccountPOM -->
      <class name="testcases.MergeAccountPOM">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcases.MergeAccountPOM@1ec1f0c]" name="beforeClass" is-config="true" duration-ms="0" started-at="2018-04-21T20:37:19Z" finished-at="2018-04-21T20:37:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="beforeMethod()[pri:0, instance:testcases.MergeAccountPOM@1ec1f0c]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-04-21T20:37:19Z" finished-at="2018-04-21T20:37:19Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:60)
	at utils.Reporter.reportStep(Reporter.java:70)
	at wdMethods.SeMethods.startApp(SeMethods.java:81)
	at wdMethods.SeMethods.startApp(SeMethods.java:86)
	at wdMethods.ProjectMethods.beforeMethod(ProjectMethods.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="SKIP" signature="mergeAccount()[pri:0, instance:testcases.MergeAccountPOM@1ec1f0c]" name="mergeAccount" duration-ms="4" started-at="2018-04-21T20:37:36Z" finished-at="2018-04-21T20:37:36Z">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
	at utils.Reporter.reportStep(Reporter.java:60)
	at utils.Reporter.reportStep(Reporter.java:70)
	at wdMethods.SeMethods.startApp(SeMethods.java:81)
	at wdMethods.SeMethods.startApp(SeMethods.java:86)
	at wdMethods.ProjectMethods.beforeMethod(ProjectMethods.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:217)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mergeAccount -->
        <test-method status="SKIP" signature="afterMethod()[pri:0, instance:testcases.MergeAccountPOM@1ec1f0c]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-04-21T20:37:36Z" finished-at="2018-04-21T20:37:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testcases.MergeAccountPOM -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
